version: '3.2'

services:

  # Message Broker
  # The settings in the docker container define
  # the vhosts, users, permissions, queues, exchanges and bindings
  mq:
    #env_file: .env.d/mq
    build: images/mq
    hostname: ega_mq
    ports:
      - "15672:15672"
    image: nbis/ega:mq
    container_name: ega_mq

  # Postgres Database
  db:
    env_file: .env.d/db
    build: images/db
    hostname: ega_db
    ports:
      - "5050:5050"
      - "5051:5051"
    container_name: ega_db
    image: nbis/ega:db
    volumes:
       - ./entrypoints/db.sh:/usr/local/bin/db.sh:ro
    entrypoint: []
    command: db.sh

  # SFTP inbox
  inbox:
    env_file: .env.d/db
    build: images/inbox
    hostname: ega_inbox
    depends_on:
      - db
      - mq
#      - monitors
    ports:
      - "2222:22"
    container_name: ega_inbox
    image: nbis/ega:inbox
    volumes:
       - ${CODE}:/root/ega
       - ${CONF}:/etc/ega/conf.ini:ro
       - inbox:/ega/inbox
       - ./entrypoints/inbox.sh:/usr/local/bin/inbox.sh:ro
    command: inbox.sh

  # ReST frontend
  frontend:
    build: images/common
    depends_on:
      - db
#      - monitors
    hostname: ega_frontend
    ports:
      - "9000:80"
    expose:
      - 80
    container_name: ega_frontend
    image: nbis/ega:common
    volumes:
       - ${CODE}:/root/ega
       - ${CONF}:/etc/ega/conf.ini:ro
       - ./entrypoints/frontend.sh:/usr/local/bin/frontend.sh:ro
    command: frontend.sh

  # Vault
  vault:
    build: images/common
    depends_on:
      - db
      - mq
#      - monitors
    hostname: ega_vault
    container_name: ega_vault
    image: nbis/ega:common
    volumes:
       - ${CODE}:/root/ega
       - ${CONF}:/etc/ega/conf.ini:ro
       - staging:/ega/staging
       - vault:/ega/vault
       - ./entrypoints/vault.sh:/usr/local/bin/vault.sh:ro
    command: vault.sh

  # # Error Monitors
  # monitors:
  #   build: images/monitors
  #   # depends_on:
  #   #   - db
  #   ports:
  #     - "10514:10514"
  #   expose:
  #     - 10514
  #   hostname: ega_monitors
  #   container_name: ega_monitors
  #   image: nbis/ega:monitors
  #   command: ["rsyslogd", "-n"]

  # Workers
  ingest:
    build: images/common
    depends_on:
      - db
      - mq
      - keys
#      - monitors
    image: nbis/ega:common
    tty: true
    stdin_open: true
    volumes:
       - ${CODE}:/root/ega
       - ${CONF}:/etc/ega/conf.ini:ro
       - inbox:/ega/inbox
       - staging:/ega/staging
       - ${SSL_CERT}:/etc/ega/ssl.cert:ro
       - ./entrypoints/ingest.sh:/usr/local/bin/ingest.sh:ro
    command: ingest.sh

  # Key server
  keys:
    build: images/common
    # depends_on:
    #   - monitors
    hostname: ega_keys
    container_name: ega_keys
    image: nbis/ega:common
    tty: true
    volumes:
       - ${CODE}:/root/ega
       - ${CONF}:/etc/ega/conf.ini:ro
       - ${KEYS}:/etc/ega/keys.ini:ro
       - ${SSL_CERT}:/etc/ega/ssl.cert:ro
       - ${SSL_KEY}:/etc/ega/ssl.key:ro
       - ${PGP_SEC}:/etc/ega/pgp/sec.key:ro
       - ${PGP_PUB}:/etc/ega/pgp/pub.key:ro
       - ${RSA_SEC}:/etc/ega/rsa/sec.pem:ro
       - ${RSA_PUB}:/etc/ega/rsa/pub.pem:ro
       - ./entrypoints/keys.sh:/usr/local/bin/keys.sh:ro
    command: ["keys.sh"]


# Use the default driver for volume creation
volumes:
  inbox:
  staging:
  vault:
