version: '3.2'

services:

  # Message Broker
  # The settings in the docker container define
  # the vhosts, users, permissions, queues, exchanges and bindings
  mq:
    #env_file: .env.d/mq
    build: images/mq
    hostname: ega-mq
    ports:
      - "15672:15672"
    image: nbis/ega:mq
    container_name: ega-mq

  # Postgres Database
  db:
    env_file: .env.d/db
    build: images/db
    hostname: ega-db
    ports:
      - "5050:5050"
      - "5051:5051"
    container_name: ega-db
    image: nbis/ega:db
    volumes:
       - ./entrypoints/db.sh:/usr/local/bin/db.sh:ro
    entrypoint: []
    command: db.sh

  # SFTP inbox
  inbox:
    env_file: .env.d/db
    build: images/inbox
    hostname: ega-inbox
    depends_on:
      - db
      - mq
#      - monitors
    ports:
      - "2222:22"
    container_name: ega-inbox
    image: nbis/ega:inbox
    volumes:
       - ${CODE}:/root/ega
       - ${CONF}:/etc/ega/conf.ini:ro
       - inbox:/ega/inbox
       - ./entrypoints/inbox.sh:/usr/local/bin/inbox.sh:ro
    command: inbox.sh

  # ReST frontend
  frontend:
    build: images/common
    depends_on:
      - db
#      - monitors
    hostname: ega-frontend
    ports:
      - "9000:80"
    expose:
      - 80
    container_name: ega-frontend
    image: nbis/ega:frontend
    volumes:
       - ${CODE}:/root/ega
       - ${CONF}:/etc/ega/conf.ini:ro
       - ./entrypoints/frontend.sh:/usr/local/bin/frontend.sh:ro
    command: frontend.sh

  # Vault
  vault:
    build: images/common
    depends_on:
      - db
      - mq
#      - monitors
    hostname: ega-vault
    container_name: ega-vault
    image: nbis/ega:common
    volumes:
       - ${CODE}:/root/ega
       - ${CONF}:/etc/ega/conf.ini:ro
       - staging:/ega/staging
       - vault:/ega/vault
       - ./entrypoints/vault.sh:/usr/local/bin/vault.sh:ro
    command: vault.sh

  # Connectors between CEGA and LEGA
  connectors:
    build: images/common
    depends_on:
      - db
      - mq
#      - monitors
    hostname: ega-connectors
    container_name: ega-connectors
    image: nbis/ega:common
    volumes:
       - ${CODE}:/root/ega
       - ${CONF}:/etc/ega/conf.ini:ro
       - ./entrypoints/connectors.sh:/usr/local/bin/connectors.sh:ro
    command: ["connectors.sh"] 
    # Exec form, not shell form

  # # Error Monitors
  # monitors:
  #   build: images/monitors
  #   # depends_on:
  #   #   - db
  #   ports:
  #     - "10514:10514"
  #   expose:
  #     - 10514
  #   hostname: ega-monitors
  #   container_name: ega-monitors
  #   image: nbis/ega:monitors
  #   command: ["rsyslogd", "-n"]

  # Workers
  worker:
    build: images/worker
    depends_on:
      - db
      - mq
      - keys
#      - monitors
    hostname: ega-worker
    container_name: ega-worker
    image: nbis/ega:worker
    tty: true
    stdin_open: true
    volumes:
       - ${CODE}:/root/ega
       - ${CONF}:/etc/ega/conf.ini:ro
       - inbox:/ega/inbox
       - staging:/ega/staging
       - ${GPG_HOME}/pubring.kbx:/root/.gnupg/pubring.kbx
       - ${GPG_HOME}/trustdb.gpg:/root/.gnupg/trustdb.gpg
       - ${GPG_HOME}/certs/selfsigned.cert:/etc/ega/ega.cert:ro
       - ${RSA_HOME}:/root/.rsa:ro
       - ./entrypoints/worker.sh:/usr/local/bin/worker.sh:ro
    command: worker.sh

  # GPG Agent
  keys:
    build: images/keys
    # depends_on:
    #   - monitors
    env_file: .env.d/gpg
    hostname: ega-keys
    container_name: ega-keys
    image: nbis/ega:keys
    tty: true
    volumes:
       - ${CODE}:/root/ega
       - ${CONF}:/etc/ega/conf.ini:ro
       - ${GPG_HOME}/pubring.kbx:/root/.gnupg/pubring.kbx
       - ${GPG_HOME}/trustdb.gpg:/root/.gnupg/trustdb.gpg
       - ${GPG_HOME}/openpgp-revocs.d:/root/.gnupg/openpgp-revocs.d:ro
       - ${GPG_HOME}/private-keys-v1.d:/root/.gnupg/private-keys-v1.d:ro
       - ${GPG_HOME}/certs/selfsigned.cert:/etc/ega/ega.cert:ro
       - ${GPG_HOME}/certs/selfsigned.key:/etc/ega/ega.key:ro
       - ${RSA_HOME}:/root/.rsa:ro
       - ./entrypoints/keys.sh:/usr/local/bin/keys.sh:ro
    command: ["keys.sh"]


# Use the default driver for volume creation
volumes:
  inbox:
  staging:
  vault:
