version: '3.0'

services:

  # Message Broker
  # The settings in the docker container define
  # the vhosts, users, permissions, queues, exchanges and bindings
  mq:
    build: ./mq
    hostname: ega-mq
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
      - "25672:25672"
    image: "ega-mq"
    container_name: "ega-mq"

  # Postgres Database
  db:
    env_file: ./details/db.env
    build: ./db
    hostname: ega-db
    ports:
      - "5432:5432"
    container_name: "ega-db"
    image: "ega-db"

  # SFTP inbox
  inbox:
    build: ./inbox
    hostname: ega-inbox
    depends_on:
      - db
      - mq
    ports:
      - "2222:22"
    container_name: "ega-inbox"
    volumes:
       - ../storage:/home
       - ..:/root/ega
       - ~/.lega/sftp.ini:/root/.lega/conf.ini
    image: "ega-inbox"
